# Generated by Django 4.1.7 on 2023-03-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=1)),
                ('numLista', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CalifLog',
            fields=[
                ('id_log', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=255)),
                ('dificultad', models.CharField(max_length=255)),
                ('calificacion', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.alumno')),
            ],
        ),
    ]
