# Generated by Django 4.1.7 on 2023-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='califlog',
            name='id_log',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
